---
title: Introduction to Undertow
layout: doc
---


Introduction to Undertow
========================
Stuart Douglas
:Author:    Stuart Douglas
:Email:     <sdouglas@redhat.com>
:Date:      2014
:Revision:  1.0

Introduction to Undertow
------------------------

Undertow is a web server designed to be used for both blocking and non-blocking tasks. Some of its main
features are:

- High Performance
- Embeddable
- Servlet 3.1
- Web Sockets
- Reverse Proxy

There and two main ways that Undertow can be used, either by directly embedding it in your code, or as part of the
link:http://www.wildfly.org[Wildfly Application Server]. This guide mostly focuses on the embedded API's, although a lot
of the content is still relevant if you are using Wildfly, it is just that the relevant functionality will generally
be exposed via XML configuration rather than programatic configuration.

The documentation is broken up into two parts, the first part focuses on Undertow code, while the second focuses on
Servlet.

[cols="3,10,3", width="100%"]
|=======
|| |link:bootstrapping.html[Next: Bootstrapping Undertow]
|=======