# Default page title
title: JBoss Community

# Project id name
project: example

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled


# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/images/example/

# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: /cache/static.jboss.org/theme/fonts
    jborg_images_url: /cache/static.jboss.org/theme/images
    jborg_js_url: /cache/static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.1/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/wildfly/scripts/bootstrap-community
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.1/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/wildfly/scripts/bootstrap-community
    base_url: http://undertow.io
    deploy:
      host: undertow@filemgmt.jboss.org
      path: /www_htdocs/undertow
  http2:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: /cache/static.jboss.org/theme/fonts
    jborg_images_url: /cache/static.jboss.org/theme/images
    jborg_js_url: /cache/static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.1/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/wildfly/scripts/bootstrap-community
    base_url: https://http2.undertow.io
asciidoc:
    attributes:
      source-highlighter: coderay
