---
title: Undertow and Netty FAQ
layout: doc
---


Undertow and Netty FAQ
======================
Stuart Douglas
:Author:    Stuart Douglas
:Email:     <sdouglas@redhat.com>
:Date:      2014
:Revision:  1

Undertow and Netty FAQ
----------------------

As the same questions regarding Netty keep coming up this page has been created to answer the common ones.

Is Undertow based on Netty
~~~~~~~~~~~~~~~~~~~~~~~~~~

No.

Undertow is based on XNIO, which is a very thin layer over Java NIO. Undertow does use Netty at build time to run some
of its Web Socket tests, however it does not use it outside the test suite.


Don't Netty and Undertow do the same thing?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

No.

According to the Netty website "Netty is an asynchronous event-driven network application framework for rapid
development of maintainable high performance protocol servers & clients."

Basically Undertow is a web server, while netty is a framework to make writing network servers easier.

Why isn't Undertow based in Netty?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Because we don't need it. Netty is designed to make network programming easier, but at the expense of another layer of
abstraction. Given that network programming is a large part of what makes up a HTTP server it does not make sense to
add in another layer of abstraction just to make things a bit easier (and given how much API breakage occurred between
Netty 3 and Netty 4 it is quite possible that it would not have made things any easier anyway).

Undertow is aiming to be the fastest web server around, and adding an additional layer of indirection would not help in that
goal.


